// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DisneyParkBooking.Data.Models
{
    public partial class Booking
    {
        public int Id { get; set; }
        public int HotelRefId { get; set; }
        public DateTime BookingStartDate { get; set; }
        public DateTime BookingEndDate { get; set; }
        public int CustomerRefId { get; set; }

        public virtual Customer CustomerRef { get; set; }
        public virtual Hotel HotelRef { get; set; }
    }
}