// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace DisneyParkBooking.Data.Models
{
    public partial class Customer
    {
        public Customer()
        {
            Bookings = new HashSet<Booking>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        [DisplayName("PAN")]
        public string IdCardPan { get; set; }

        public virtual ICollection<Booking> Bookings { get; set; }
    }
}